# openapi: 3.1.0
# info:
#   version: 1.0.0
#   title: Tasteorama app
#   license:
#     name: Apache 2.0
#     url: http://www.apache.org/licenses/LICENSE-2.0.html
#   description: This is a documentation of Tasteorama app
# tags:
#   - name:
#     description: Operations about users.
#   - name: Auth
#     description: Auth operations.
# servers:
#   - url: http://localhost:3000
#   - url:

# paths:
#
#
#   /auth/logout:
#     post:
#       $ref: ../swagger/paths/auths/logout.yaml
#
# components:
#   securitySchemes:
#     bearerAuth:
#       type: http
#       scheme: bearer
